cdad/cdad/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from cdadmap import urls

urlpatterns = patterns('',    
    url(r'^', include('cdadmap.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^select2/', include('django_select2.urls')),
)

cdad/cdadmap/urls.py
from django.conf.urls import patterns, include, url
from cdadmap import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^filter/$', views.filterLocations, name='filterLocations'),
    url(r'^getlocationdataforcdobclayer/$', views.getLocationDataForCDOBCLAYER, name='getLocationDataForCDOBCLAYER'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^survey/$', views.surveyPage1, name='surveyView'),
    url(r'^survey/(?P<id>\d+)/$', views.surveyPage1, name='surveyView'),
    url(r'^adminsurvey/$', views.adminSurveyPage1, name='adminSurveyView'),
    url(r'^adminsurvey/(?P<id>\d+)/$', views.adminSurveyPage1, name='adminSurveyView'),
    url(r'^survey2/(?P<id>\d+)/$', views.surveyPage2, name='surveyPage2'),
    url(r'^survey3/(?P<id>\d+)/$', views.surveyPage3, name='surveyPage3'),
    url(r'^survey4/(?P<id>\d+)/$', views.surveyPage4, name='surveyPage4'),
    url(r'^survey5/(?P<id>\d+)/$', views.surveyPage5, name='surveyPage5'),
    url(r'^survey6/(?P<id>\d+)/$', views.surveyPage6, name='surveyPage6'),
    url(r'^survey7/(?P<id>\d+)/$', views.surveyPage7, name='surveyPage7'),
    url(r'^getjsonformap/(?P<id>\d+)/$', views.getJSONforMap, name='getJSONforMap'),
    url(r'^survey7save/(?P<id>\d+)/$', views.surveyPage7save, name='surveyPage7save'),
    url(r'^survey8/(?P<id>\d+)/$', views.surveyPage8, name='surveyPage8'),
    url(r'^survey9/(?P<id>\d+)/$', views.surveyPage9, name='surveyPage9'),
    url(r'^survey10/(?P<id>\d+)/$', views.surveyPage10, name='surveyPage10'),
    url(r'^survey11/(?P<id>\d+)/$', views.surveyPage11, name='surveyPage11'),
    url(r'^survey12/(?P<id>\d+)/$', views.surveyPage12, name='surveyPage12'),
    url(r'^survey13/(?P<id>\d+)/$', views.surveyPage13, name='surveyPage13'),
    url(r'^survey14/(?P<id>\d+)/$', views.surveyPage14, name='surveyPage14'),
    url(r'^surveyfinish/(?P<id>\d+)/$', views.surveyfinish, name='surveyfinish'),
    url(r'^verifysurvey/(?P<id>\d+)/$', views.verifysurvey, name='verifysurvey'),
    url(r'^removesurvey/(?P<id>\d+)/$', views.removesurvey, name='removesurvey'),
    url(r'^removesurveyyep/(?P<id>\d+)/$', views.removesurveyyep, name='removesurveyyep'),
    url(r'^adminregister/$', views.adminRegister, name='adminRegister'),
    url(r'^administeraccounts/$', views.administerAccounts, name='administerAccounts'),
    url(r'^removeuser/(?P<id>\d+)/$', views.removeUsers, name='removeUsers'),
    url(r'^removeuseryep/(?P<id>\d+)/$', views.removeUsersYep, name='removeUsersYep'),
    url(r'^downloaddata/$', views.downloaddata, name='downloaddata'),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cdad/cdadmap/models.py
from django.db import models
# import User model
from django.contrib.auth.models import User
import datetime

# CDAD models below

#names of partners
class Partners(models.Model):
    partner_name = models.CharField(max_length=255, default='', unique=True)

    def __str__(self):
        return self.partner_name        


# Survey model retired
class Survey(models.Model):
    id = models.AutoField(primary_key=True)
    Organization_Name = models.TextField()
    Organizaton_Acronym = models.TextField()
    Survey_Taker_Name = models.TextField()
    Survey_Taker_Email_Address = models.TextField()
    Survey_Taker_Email_AddToList = models.TextField()
    Organization_Description = models.TextField()
    Year_Founded = models.TextField()
    Organization_Logo = models.TextField()
    Organizational_Mission = models.TextField()
    Social_Email = models.TextField()
    AddSocial_Email = models.TextField()
    Social_facebook = models.TextField()
    Social_website = models.TextField()
    Social_Twitter = models.TextField()
    Social_other_media = models.TextField()
    Service_Area_Description = models.TextField()
    Service_Area_Geographic_Boundaries = models.TextField()
    MapDissolve = models.TextField()
    organization_structured = models.TextField()
    governance_board = models.TextField()
    No_of_board_members = models.TextField()
    staff_members = models.TextField()
    Activities_Services = models.TextField()
    Service_Population = models.TextField()
    Languages = models.TextField()
    accomplish_one_title = models.TextField()
    accomplish_one_description = models.TextField()
    accomplish_two_title = models.TextField()
    accomplish_two_description = models.TextField()
    accomplish_three_title = models.TextField()
    accomplish_three_description = models.TextField()
    accomplish_four_title = models.TextField()
    accomplish_four_description = models.TextField()
    accomplish_five_title = models.TextField()
    accomplish_five_description = models.TextField()
    CDAD_MemberShip = models.TextField()
    CDAD_Services = models.TextField()
    CDAD_Comments = models.TextField()
    CDAD_FeedBack = models.TextField()
    MyTrace = models.IntegerField(default=0)
        
    class Meta:
        db_table = 'survey'

    def __str__(self):
        return self.Organization_Name        


# Default user for syncing, users can be linked to surveys later
DEFAULT_USER_ID = 1

# SurveyPanel defined first to allow foreign key relationship to come late        
class SurveyPanel(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, default=DEFAULT_USER_ID)
    verified = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    removed = models.BooleanField(default=False)
    Organization_Name = models.CharField(max_length=255, default='', unique=True)
    Organizaton_Acronym = models.TextField()
    Survey_Taker_Name = models.TextField()
    Survey_Taker_Email_Address = models.TextField()
    Survey_Taker_Email_AddToList = models.TextField()
    Organization_Description = models.TextField()
    Organization_Description_Other = models.CharField(max_length=255, default='', null=True, blank=True)
    Year_Founded = models.TextField()
    Organization_Logo = models.TextField()
    Organization_Logo_Image = models.ImageField(upload_to="img/%Y_%m_%d_%h_%M_%s", null=True, blank=True)
    Organizational_Mission = models.TextField()
    Social_Email = models.TextField()
    AddSocial_Email = models.TextField()
    Social_Phone = models.CharField(max_length=20, default='')
    Social_Phone_KeepPrivate = models.BooleanField(default=False)
    Social_facebook = models.URLField(max_length=2000, null=True, blank=True)
    Social_website = models.URLField(max_length=2000, null=True, blank=True)
    Social_Twitter = models.URLField(max_length=2000, null=True, blank=True)
    youtube = models.URLField(max_length=2000, null=True, blank=True)
    instagram = models.URLField(max_length=2000, null=True, blank=True)
    nextdoor = models.URLField(max_length=2000, null=True, blank=True)
    Social_other_media = models.TextField()
    Service_Area_Description = models.TextField()
    Service_Area_Geographic_Boundaries = models.TextField()
    CouncilDistricts = models.TextField()
    MapDissolve = models.TextField()
    organization_structured = models.TextField()
    governance_board = models.TextField()
    No_of_board_members = models.TextField()
    staff_members = models.TextField()
    Activities_Services = models.TextField()
    Service_Population = models.TextField()
    Service_Population_Other = models.CharField(max_length=255, default='', null=True, blank=True)
    Languages = models.TextField()
    Languages_Other = models.TextField(null=True, blank=True)
    accomplish_one_title = models.TextField()
    accomplish_one_description = models.TextField()
    accomplish_two_title = models.TextField(null=True, blank=True)
    accomplish_two_description = models.TextField(null=True, blank=True)
    accomplish_three_title = models.TextField(null=True, blank=True)
    accomplish_three_description = models.TextField(null=True, blank=True)
    accomplish_four_title = models.TextField(null=True, blank=True)
    accomplish_four_description = models.TextField(null=True, blank=True)
    accomplish_five_title = models.TextField(null=True, blank=True)
    accomplish_five_description = models.TextField(null=True, blank=True)
    CDAD_MemberShip = models.TextField()
    CDAD_Services = models.TextField()
    CDAD_Services_Other = models.CharField(max_length=255, default='', null=True, blank=True)
    CDAD_Comments = models.TextField(null=True, blank=True)
    CDAD_FeedBack = models.TextField(null=True, blank=True)
    partners = models.ManyToManyField(Partners, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True) 

    class Meta:
        db_table = 'surveyPanel'

    def __str__(self):
        return self.Organization_Name


class Contact(models.Model):
    id = models.AutoField(primary_key=True)
    Organization_Name = models.TextField()
    Name = models.TextField()
    Title = models.TextField()
    Tel = models.TextField()
    Email = models.TextField()
    KeepPrivate = models.TextField()
    AddListPermission = models.TextField()
    MyTrace = models.IntegerField(default=0)

    class Meta:
        db_table = 'contact'
        
    def __str__(self):
        return self.Organization_Name
        

class ContactPanel(models.Model):
    id = models.AutoField(primary_key=True)
    Organization_Name = models.TextField()
    Name = models.TextField()
    Title = models.TextField()
    Tel = models.TextField()
    Email = models.TextField()
    KeepPrivateTel = models.BooleanField(default=False)
    KeepPrivateEmail = models.BooleanField(default=False)
    AddListPermission = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'contactPanel'

    def __str__(self):
        return self.Organization_Name


class Meeting(models.Model):
    id = models.AutoField(primary_key=True)
    Organization_Name = models.TextField()
    hasMeeting = models.TextField()
    MeetingName = models.TextField()
    Address = models.TextField()
    Address2 = models.TextField()
    City = models.TextField()
    ZipCode = models.TextField()
    State = models.TextField()
    Repeat1 = models.TextField()
    RepeatEvery = models.TextField()
    Time1 = models.TextField()
    StartOn = models.TextField()
    EndsOn = models.TextField()
    Occurances = models.TextField()
    On1 = models.TextField()
    MeetingPerson = models.TextField()
    MeetingPersonPhone = models.TextField()
    MeetingPersonEmail = models.TextField()
    MeetAlways = models.TextField()
    MyTrace = models.IntegerField(default=0)

    class Meta:
        db_table = 'meeting'

    def __str__(self):
        return self.Organization_Name

REPEAT_CHOICES = (
    ('NEVER', 'Never'),
    ('DAILY', 'Every Day'),
    ('WEEKDAY', 'Every Weekday'),
    ('WEEKLY', 'Every Week'),
    ('MONTHLY', 'Every Month'),
    ('YEARLY', 'Every Year'),
)


class MeetingPanel(models.Model):
    id = models.AutoField(primary_key=True)
    Organization_Name = models.TextField()
    hasMeeting = models.BooleanField(default=False)
    MeetingName = models.TextField()
    Address = models.TextField()
    Address2 = models.TextField(null=True, blank=True)
    City = models.TextField()
    ZipCode = models.TextField()
    State = models.TextField()
    all_day = models.BooleanField(default=False)
    repeat = models.CharField(max_length=15, choices=REPEAT_CHOICES, default='NEVER')
    end_repeat = models.DateField(null=True, blank=True)
    StartOn = models.DateTimeField()
    EndsOn = models.DateTimeField()
    MeetingPerson = models.TextField()
    MeetingPersonPhone = models.TextField()
    MeetingPersonEmail = models.TextField()
    MeetAlways = models.BooleanField(default=False)

    class Meta:
        db_table = 'meetingpanel'

    def __str__(self):
        return self.Organization_Name

    def getStartWeekDay(self):
        day_of_month = self.StartOn.day
        week_number = (day_of_month - 1) // 7 + 1
        if week_number == 1:
            week_number = '1st'
        elif week_number == 2:
            week_number = '2nd'
        elif week_number == 3:
            week_number = '3rd'
        else:
            week_number = str(week_number) + 'th'
        return week_number

    def checkRepeat(self):
        if datetime.datetime.now().day < self.end_repeat.day:
            return True
        return False


class Location(models.Model):
    id = models.AutoField(primary_key=True)
    Organization_Name = models.TextField()
    Address = models.TextField()
    Address2 = models.TextField()
    City = models.TextField()
    ZipCode = models.TextField()
    State = models.TextField()
    MailingAddress = models.TextField()

cdad/cdadmap/templates/cdadsurvey/admin_dashboard.html
{% extends 'cdadsurvey/base.html' %}
{% load staticfiles %}
{% load cdad_filters %}

{% block css_block %}
<link rel="stylesheet" type="text/css" href="{% static 'cdadmap/css/bootstrap-sortable.css' %}">
{% endblock %}

{% block head_js_block %}
{% endblock %}
	

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3>Admin Dashboard</h3>
      <a class="btn btn-default btn-lg" href="/adminsurvey/" role="button">Create a New Survey</a>
      <a class="btn btn-default btn-lg" href="{% url 'registration_register' %}" role="button">Register a New User</a>
      <a class="btn btn-default btn-lg" href="{% url 'adminRegister' %}" role="button">Register an Administrator</a>
      <a class="btn btn-default btn-lg" href="{% url 'downloaddata' %}" role="button">Export Survey Data</a>
      {% if user|has_group:"superadmin" %}
      <a class="btn btn-default btn-lg" href="{% url 'administerAccounts' %}" role="button">Administer Accounts</a>
      {% endif %}
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-condensed sortable">
		    <thead>
		      <th>Status</th>
		      <th>Edit</th>
		      <th>Remove</th>
		      <th>Organization Name</th>
		      <th>Acronym</th>
		      <th>User Account</th>
		      <th>Survey Taker Name & Email</th>
		      <th>Created</th>
		      <th>Modified</th>
		    </thead>
		    <tbody>
		      {% for survey in surveyObjects %}
		        <tr>
		          <td>
		            {% if survey.verified %}
		              <p class="text-success"><strong>VERIFIED</strong> <small><a href="/verifysurvey/{{ survey.id }}/">Remove verification?</a></small></p>
		            {% elif survey.removed %}
		              <p class="text-danger"><strong>REMOVED</strong> <small><a href="/removesurvey/{{ survey.id }}/">Recover?</a> <a href="/removesurveyyep/{{ survey.id }}/">Remove Permanantly? (Careful, this removes this survey immediately!)</a></small></p>
		            {% elif survey.completed %}
		              <a class="btn btn-warning" href="/verifysurvey/{{ survey.id }}/" role="button">Awaiting Verification</a>
		            {% else %}
		              <p class="text-info"><strong>IN PROGRESS</strong></p>
		            {% endif %}
		          </td>
		          <td>
		          	<a class="btn btn-default" href="/adminsurvey/{{ survey.id }}" role="button">Edit</a>
		          </td>
		          <td>
		          	<a class="btn btn-danger" href="/removesurvey/{{ survey.id }}" role="button">Remove</a>
		          </td>
		          <td>{{ survey.Organization_Name }}</td>
		          <td>{{ survey.Organizaton_Acronym }}</td>
		          <td>
		            {{ survey.user.username }} ({{ survey.user.email }})
		          </td>
		          <td>
		            {{ survey.Survey_Taker_Name }} ({{ survey.Survey_Taker_Email_Address }})
		          </td>
		          <td>{{ survey.created }}</td>
		          <td>{{ survey.modified }}</td>
		        </tr>
		      {% endfor %}
		    </tbody>
		  </table>
    </div>
  </div>
</div> <!-- /container -->
{% endblock %}


{% block js_block %}
<script type="text/javascript" src="{% static 'cdadmap/js/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'cdadmap/js/bootstrap-sortable.js' %}"></script>
{% endblock %}





	
	

cdad/cdadmap/templates/cdadsurvey/surveyPage1.html
{% extends 'cdadsurvey/base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}

{% block css_block %}
{% endblock %}

{% block head_js_block %}
{% endblock %}
	

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-11">
      <h3>General Organization Information</h3>
		<form method="post" action=".">
			{% csrf_token %}
			{{ form|as_bootstrap }}
			<input type="submit" class="btn btn-primary" value="Save and Continue" />
		</form>
    </div>
	<div class="col-md-1">
		<div class="percent">
			<em>0</em>
			<sup>%</sup>
		</div>
	</div>
  </div>
</div> <!-- /container -->


{% endblock %}

{% block modal_block %}
<!-- ajax loading page modal -->
<div class="modal fade" id="introductionSurvey" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body modalContent">
      	<h3 class="text-center text-uppercase">A note to survey participants</h3>
      	<p class="text-justify">
	      	Again, thank you for participating in d[COM]munity! If you get started on the survey, but need to finish later, you can save your progress and return at a later time to finish with your login information.  Once the survey is submitted to d[COM]munity you will be able to use the same login information to edit and update the information as necessary.	
		</p>
		<div class="clearfix"></div>
        <button id="closeIntroModalSurvey" class="btn btn-primary btn-lg center-block" type="submit">Begin the Survey</button>
        <div class="checkbox text-center text-uppercase">
		  <label>
		    <input type="checkbox" id="toggleIntroCookieSurvey" value="NoShow" checked>
		   Don't Show This Message
		  </label>
		</div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js_block %}

	<script type="text/javascript" src="{% static 'cdadmap/js/jquery.cookie.js' %}"></script>

	<!-- open introductory modal on page load -->
	<script type="text/javascript">
		$( document ).ready(function() {
			if (!$.cookie('noIntroSurvey')) {
				$('#introductionSurvey').modal('show');
				// close if button clicked
				$('#closeIntroModalSurvey').click(function() {
					$('#introductionSurvey').modal('hide');
				});
				// set cookie if don't show this message is checked
				$('#toggleIntroCookieSurvey').change(function() {
					if($(this).is(":checked")) {
						$.cookie('noIntroSurvey', 'noIntroSurvey', { expires: 365, path: '/' });
					} else {
						$.removeCookie('noIntroSurvey', { path: '/' });
					}
				});
			}
			// set cookie on page load -- remove only if user elects to remove
			$.cookie('noIntroSurvey', 'noIntroSurvey', { expires: 365, path: '/' });

			// hide other field if not checked
			if (!$('#id_Organization_Description_7').is(':checked')) {
				$('#div_id_Organization_Description_Other').addClass('hidden');
			}

			$('#id_Organization_Description_7').change(function() {
				if ($(this).is(':checked')) {
					$('#div_id_Organization_Description_Other').removeClass('hidden');
				} else {
					$('#div_id_Organization_Description_Other').addClass('hidden');
					// remove text from field
					$('#id_Organization_Description_Other').val('');
				}				
			});

		});
	</script>
{% endblock %}





	
	

cdad/cdadmap/templates/cdadsurvey/surveyPage10.html
{% extends 'cdadsurvey/base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}

{% block css_block %}
{% endblock %}

{% block head_js_block %}
{% endblock %}
	

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-11">
      <h3>Programs and Activities</h3>
		<form method="post" action=".">
			{% csrf_token %}
			{{ form|as_bootstrap }}
			<a class="btn btn-default" href="/survey9/{{ id }}/">Back</a>
			<input type="submit" class="btn btn-primary" value="Save and Continue" />
		</form>
    </div>
	<div class="col-md-1">
		<div class="percent">
			<em>64</em>
			<sup>%</sup>
		</div>
	</div>
  </div>
</div> <!-- /container -->
{% endblock %}


{% block js_block %}
<script type="text/javascript">
	$( document ).ready(function() {
		if (!$('#id_Service_Population_15').is(':checked')) {
			$('#div_id_Service_Population_Other').addClass('hidden');
		}

		$('#id_Service_Population_15').change(function() {
			if ($(this).is(':checked')) {
				$('#div_id_Service_Population_Other').removeClass('hidden');
			} else {
				$('#div_id_Service_Population_Other').addClass('hidden');
				// remove text from field
				$('#id_Service_Population_Other').val('');
			}
			
		});

	});
</script>
{% endblock %}


	
	

cdad/cdadmap/templates/cdadsurvey/surveyPage13.html
{% extends 'cdadsurvey/base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% load django_select2_tags %}

{% block css_block %}
{% import_django_select2_css %}
{% endblock %}

{% block head_js_block %}
{% endblock %}
	

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-11">
      <h3>Partnerships and Networks</h3>
      <p>Please check all the organizations, groups, or other entities with whom your organization has partnered in the last three years. You may select fron the Detroit organizations listed below or add others that are not on the list.</p>
		<form method="post" action=".">
			{% csrf_token %}
			{{ form|as_bootstrap }}
			<p>For a list of examples of partners please visit the <a href="http://cdad-online.org/membership/member-directory/">CDAD Member Directory</a>.</p>
			<h4>Add Partners Not in List Above</h4>
			{{ formset.management_form }}
			{% for form in formset %}
	        	{{ form|as_bootstrap }}
	        {% endfor %}
			<a class="btn btn-default" href="/survey12/{{ id }}/">Back</a>
			<input type="submit" class="btn btn-primary" value="Save and Continue" />
		</form>
    </div>
	<div class="col-md-1">
		<div class="percent">
			<em>86</em>
			<sup>%</sup>
		</div>
	</div>
  </div>
</div> <!-- /container -->
{% endblock %}

{% block js_block %}
{% import_django_select2_js %}

<script type="text/javascript">
	$( document ).ready(function() {
		$('.help-block').addClass('hidden');

		// sort the select list
		$('#id_partners').select2({
		    sortResults: function(results, container, query) {
		    	function sort(a,b){
				    a = a.text.toLowerCase();
				    b = b.text.toLowerCase();
				    if(a > b) {
				        return 1;
				    } else if (a < b) {
				        return -1;
				    }
				    return 0;
				}
				results.sort(sort);

	            return results;
		    }
		});

	});
</script>

{% endblock %}





	

cdad/cdadmap/templates/cdadsurvey/surveyPage14.html
{% extends 'cdadsurvey/base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}

{% block css_block %}
{% endblock %}

{% block head_js_block %}
{% endblock %}
	

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-11">
      <h3>Who is CDAD?</h3>
      <p>As Detroit's association of Community Development and Neighborhood Improvement Organizations, Community Development Advocates of Detroit (CDAD) is a catalyst for the trasformation of our neighborhoods, led and inspired by residents, community-based organizations, and ohter community stakeholders.</p>
      <p>CDAD works to enhance the capacity and effectiveness of Detroit's commmunity-based organizations, initiatives, and residents through advocacy, training, technical assistance, networking opportunities, information sharing, and facilitating common action.</p>
		<form method="post" action=".">
			{% csrf_token %}
			{{ form|as_bootstrap }}
			<a class="btn btn-default" href="/survey13/{{ id }}/">Back</a>
			<input type="submit" class="btn btn-primary" value="Save and Continue" />
		</form>
    </div>
	<div class="col-md-1">
		<div class="percent">
			<em>93</em>
			<sup>%</sup>
		</div>
	</div>
  </div>
</div> <!-- /container -->
{% endblock %}

{% block js_block %}
<script type="text/javascript">
	$( document ).ready(function() {
		if (!$('#id_CDAD_Services_6').is(':checked')) {
			$('#div_id_CDAD_Services_Other').addClass('hidden');
		}

		$('#id_CDAD_Services_6').change(function() {
			if ($(this).is(':checked')) {
				$('#div_id_CDAD_Services_Other').removeClass('hidden');
			} else {
				$('#div_id_CDAD_Services_Other').addClass('hidden');
				// remove text from field
				$('#id_CDAD_Services_Other').val('');
			}
			
		});

	});
</script>
{% endblock %}






	
	

cdad/cdadmap/templates/cdadsurvey/surveyPage4.html
{% extends 'cdadsurvey/base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}

{% block css_block %}
{% endblock %}

{% block head_js_block %}
{% endblock %}
	

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-11">
      <h3>Organization Contact Information</h3>
		<form method="post" action=".">
			{% csrf_token %}
			{{ form|as_bootstrap }}
			<a class="btn btn-default" href="/survey2/{{ id }}/">Back</a>
			<input type="submit" class="btn btn-primary" value="Save and Continue" />
		</form>
    </div>
	<div class="col-md-1">
		<div class="percent">
			<em>21</em>
			<sup>%</sup>
		</div>
	</div>
  </div>
</div> <!-- /container -->

{% endblock %}



	
	

cdad/cdadmap/templates/cdadsurvey/surveyPage8.html
{% extends 'cdadsurvey/base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}

{% block css_block %}
{% endblock %}

{% block head_js_block %}
{% endblock %}
	

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-11">
      <h3>Organizational Structure</h3>
		<form method="post" action=".">
			{% csrf_token %}
			{{ form|as_bootstrap }}
			<a class="btn btn-default" href="/survey7/{{ id }}/">Back</a>
			<input type="submit" class="btn btn-primary" value="Save and Continue" />
		</form>
    </div>
	<div class="col-md-1">
		<div class="percent">
			<em>50</em>
			<sup>%</sup>
		</div>
	</div>
  </div>
</div> <!-- /container -->
{% endblock %}

{% block js_block %}
<script type="text/javascript">
	$( document ).ready(function() {
		// if no is selected, add 0 to board member number values
		$('#id_governance_board_2').click(function(e) {
			$('#id_No_of_board_members').val(0);
		});
	});
</script>


{% endblock %}




	
	

cdad/cdadmap/templates/cdadsurvey/surveyPage9.html
{% extends 'cdadsurvey/base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}

{% block css_block %}
{% endblock %}

{% block head_js_block %}
{% endblock %}
	

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-11">
      <h3>Programs and Activities</h3>
		<form method="post" action=".">
			{% csrf_token %}
			{{ form|as_bootstrap }}
			<a class="btn btn-default" href="/survey8/{{ id }}/">Back</a>
			<input type="submit" class="btn btn-primary" value="Save and Continue" />
		</form>
    </div>
	<div class="col-md-1">
		<div class="percent">
			<em>57</em>
			<sup>%</sup>
		</div>
	</div>
  </div>
</div> <!-- /container -->
{% endblock %}





	
	